import React from 'react';
import Modal from './Modal';
import { Printer, CheckCircle2, ShieldCheck, Download } from 'lucide-react';

export default function ReceiptModal({ isOpen, onClose, txn }) {
  if (!txn) return null;

  const handlePrint = () => {
    window.print();
  };

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Official Financial Voucher" subtitle="Accounting Audit Trail & Confirmation" maxWidth="max-w-md">
      <div id="receipt-print-area" className="p-2 space-y-5">
        {/* Header Voucher */}
        <div className="text-center pb-4 border-b border-dashed border-slate-200">
          <div className="w-12 h-12 mx-auto bg-emerald-100 text-emerald-600 rounded-full flex items-center justify-center mb-2">
            <CheckCircle2 className="w-6 h-6" />
          </div>
          <h2 className="text-lg font-extrabold text-slate-900 tracking-tight">ABLE INVEST LTD</h2>
          <p className="text-xs text-slate-500">Licensed Financial Schemes & Asset Management</p>
          <div className="mt-2 text-2xl font-black text-slate-900">
            ₦{Number(txn.amount || 0).toLocaleString()}
          </div>
          <span className="inline-block mt-1 px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-50 text-emerald-700 border border-emerald-200">
            {txn.status || 'VERIFIED'}
          </span>
        </div>

        {/* Ledger Breakdown Details */}
        <div className="space-y-3 text-xs">
          <div className="flex justify-between py-1 border-b border-slate-100">
            <span className="text-slate-500">Transaction Reference</span>
            <span className="font-mono font-bold text-slate-800">{txn.txn_ref || txn.reference || 'N/A'}</span>
          </div>
          <div className="flex justify-between py-1 border-b border-slate-100">
            <span className="text-slate-500">Account / Entity</span>
            <span className="font-semibold text-slate-800">{txn.account_title || txn.user_name || 'Customer Account'}</span>
          </div>
          <div className="flex justify-between py-1 border-b border-slate-100">
            <span className="text-slate-500">Transaction Type</span>
            <span className="font-semibold text-slate-800 uppercase">{txn.txn_type}</span>
          </div>
          <div className="flex justify-between py-1 border-b border-slate-100">
            <span className="text-slate-500">Account Category</span>
            <span className="font-semibold text-slate-800">{txn.account_type || 'LEDGER'}</span>
          </div>
          <div className="flex justify-between py-1 border-b border-slate-100">
            <span className="text-slate-500">Payment Channel</span>
            <span className="font-semibold text-slate-800">{txn.payment_method || 'Electronic Wire'}</span>
          </div>
          <div className="flex justify-between py-1 border-b border-slate-100">
            <span className="text-slate-500">Timestamp</span>
            <span className="font-medium text-slate-700">{new Date(txn.created_at || Date.now()).toLocaleString()}</span>
          </div>
          <div className="flex justify-between py-1 border-b border-slate-100">
            <span className="text-slate-500">Audit Status</span>
            <span className="font-semibold text-emerald-600 flex items-center gap-1">
              <ShieldCheck className="w-3.5 h-3.5" /> Ledger Reconciled
            </span>
          </div>
          {txn.notes && (
            <div className="py-2 bg-slate-50 p-2.5 rounded-xl text-slate-600 italic">
              "{txn.notes}"
            </div>
          )}
        </div>

        {/* Security watermark footer */}
        <div className="text-center pt-2 text-[11px] text-slate-400">
          This document represents an immutable double-entry ledger event generated by ABLE INVEST accounting system.
        </div>

        {/* Actions */}
        <div className="flex gap-2 pt-2 no-print">
          <button
            onClick={handlePrint}
            className="flex-1 py-2.5 px-4 bg-slate-900 text-white rounded-xl text-xs font-semibold hover:bg-slate-800 flex items-center justify-center gap-2 transition"
          >
            <Printer className="w-4 h-4" /> Print Voucher
          </button>
          <button
            onClick={onClose}
            className="py-2.5 px-4 bg-slate-100 text-slate-700 rounded-xl text-xs font-semibold hover:bg-slate-200 transition"
          >
            Close
          </button>
        </div>
      </div>
    </Modal>
  );
}
